apiVersion: apps/v1
kind: Deployment
metadata:
  name: andliin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: andliin
  template:
    metadata:
      labels:
        app: andliin
    spec:
      containers:
      - image: okteto.dev/andliin:latest
        name: andliin
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/andliin/main/S-html.zip"
        - name: Vless_UUID
          value: "486c37ed-5066-4496-8a8c-281c5f8bc367"
        - name: Vless_Path
          value: "/vjhs83hgbdf5"
        - name: Vmess_UUID
          value: "486c37ed-5066-4496-8a8c-281c5f8bc367"
        - name: Vmess_Path
          value: "/vmpb93brwzxa6"
        - name: Share_Path
          value: "/v2link"
